config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :jobs
  resources :resources
  resources :consumptions
  resources :relations

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/gtc', to: 'static_pages#gtc'

  match 'resources/new_project', :to => 'resources#new_project'
  match 'users/update_project', :to => 'users#update_project'
  match 'jobs/delete_solution', :to => 'jobs#delete_solution'
  match 'jobs/solve_problem', :to => 'jobs#solve_problem'
  match 'jobs/load_project', :to => 'jobs#load_project'

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :begin, :duration, :end, :fez, :name, :sez, :ssz
  validates :duration, presence: true, :numericality => { :greater_than => 0}
  validates :name, presence: true, length: {minimum: 5, maximum: 45},  uniqueness: { case_sensitive: false }

  has_many :consumptions
  has_many :relations, foreign_key: "job_id"
  has_many :relations, foreign_key: "successor_id"
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :signed_in_user
  before_filter :admin_user,     only: :load_project


  def index
    @jobs = Job.all
    respond_to do |format|
      format.html # index.html.erb
      format.json {render json: @jobs}
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new (params[:job])
    if @job.save
      flash[:success] = "Job saved!"
      redirect_to jobs_path
    else
      render 'new'
    end
  end


  def update
    @job = Job.find(params[:id])

    if @job.update_attributes(params[:job])
      flash[:success] = "Update successful!"
      redirect_to jobs_path

    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:success] = "Job destroyed."
    redirect_to jobs_path
  end


  def load_project
    if File.exists?("Outputfile.txt")
      File.delete("Outputfile.txt")
    end
    system "rake db:reset_data"
    system "rake db:sample_project"
    flash[:success] = "Sample Project loaded!"
    redirect_to current_user
  end

  def solve_problem
    @jobs = Job.all
    @jobs.each { |jo|
      jo.fez = jo.duration
      @relations = Relation.all
      @relations.each {|re|
        if jo.id == re.successor_id
          if jo.fez < re.job.fez+jo.duration
            jo.fez = re.job.fez + jo.duration
          end
        end
        jo.save
      }
    }

    @jobs.each{|jo|
      jo.sez = Job.maximum('fez')
      @relations.each{|re|
        if jo.id == re.job_id
          jo.sez = Job.sum('duration')
        end
        jo.save
      }
    }

    @jobs.reverse_each{|jo|
      @relations.each{|re|
        if jo.id == re.job_id
          if jo.sez >= (re.successor.sez-re.successor.duration) then
            jo.sez = re.successor.sez-re.successor.duration
            jo.save
          end
        end
      }
    }

    if File.exist?("Inputfile.inc")
      File.delete("Inputfile.inc")
    end

    f=File.new("Inputfile.inc", "w")

    printf(f, "set r / \n")
    @resources = Resource.all
    @resources.each { |res| printf(f, "r" + res.id.to_s + "\n") }
    printf(f, "/; \n\n")

    printf(f, "set j / \n")
    printf(f, "Q \n")
    @jobs = Job.all
    @jobs.each { |jo| printf(f, "j"+jo.id.to_s + "\n" ) }
    printf(f, "S \n")
    printf(f, "/; \n\n")

    printf(f, "set t /t0*t"+Job.sum(:duration).to_s+"/; \n\n")

    printf(f, "VN(h,j)=no; \n")
    @jobs.each do |jo|
      printf(f, "VN('Q','j" + jo.id.to_s + "')=yes;\n")
      printf(f, "VN('j" + jo.id.to_s + "','S')=yes;\n" )
    end
    printf(f, "\n")

    @relations = Relation.all
    @relations.each { |rel| printf(f, "VN('j"+ rel.job.id.to_s + "','j" + rel.successor.id.to_s + "')=yes; \n") }
    printf(f, "\n")

    printf(f, "parameter \n")
    printf(f, "d(j) / \n")
    printf(f, "Q   0\n")
    printf(f, "S   0\n")
    @jobs = Job.all
    @jobs.each { |jo| printf(f, "j"+jo.id.to_s + "   " + jo.duration.to_s + "\n") }
    printf(f, "/\n")

    printf(f, "FEZ(j) /\n")
    printf(f, "Q   0\n")
    printf(f, "S   0\n")
    @jobs = Job.all
    @jobs.each {|jo| printf(f, "j"+jo.id.to_s + "   " + jo.fez.to_s + "\n" ) }
    printf(f, "/\n")

    printf(f, "SEZ(j) /\n")
    printf(f, "Q   0\n")
    printf(f, "S "+ Job.sum(:duration).to_s+"\n")
    @jobs = Job.all
    @jobs.each {|jo| printf(f, "j"+jo.id.to_s + "   " + jo.sez.to_s + "\n" ) }
    printf(f, "/\n")

    printf(f, "Kap(r) /\n")
    @resources.each { |res| printf(f, "r"+res.id.to_s+ "   " + res.capacity.to_s + "\n" ) }
    printf(f, "/;\n\n")

    printf(f, "k(j,r)=0;\n")
    @consumptions = Consumption.all
    @consumptions.each { |con| printf(f,"k('j"+con.job.id.to_s+"','r" + con.resource.id.to_s + "')=" + con.consumption.to_s+";\n")}
    f.close

    if File.exist?("Outputfile.txt")
      File.delete("Outputfile.txt")
    end

    system "C:\\GAMS\\win64\\24.1\\gams RCPSP_Modell"

    if File.exists?("Outputfile.txt")
      flash[:success] = "Optimization done!"
    else
      flash[:error] = "Optimization failed"
    end

    if File.exist?("Outputfile.txt")
      fi=File.open("Outputfile.txt", "r")
      line=fi.readline
      sa=line.split(" ")
      @objective_function_value=sa[1]
      fi.each { |line|
        sa=line.split(";")
        sa0=sa[0].delete "j "
        sa1=sa[1].delete " \n"
        al=Job.find_by_id(sa0)
        al.end=sa1.to_i-1
        al.begin=sa1.to_i-1-al.duration
        al.save
      }
      fi.close
      @jobs = Job.all
      render "jobs/index"

    else
      flash.now[:not_available] = "Problem not solved!"
      @jobs = Job.all
      redirect_to current_user
    end
  end

   def delete_solution
    if File.exists?("Outputfile.txt")
      File.delete("Outputfile.txt")
    end

    @jobs = Job.all
    @jobs.each { |jo|
      jo.fez=nil
      jo.sez=nil
      jo.begin=nil
      jo.end=nil
      jo.save
    }

    @objective_function_value=nil
    flash[:success] = "Solution destroyed!"
    redirect_to current_user
  end



  private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/views/jobs/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@job) do |f| %>
        <% if @job.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

              <ul>
                <% @job.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label 'Name' %>
          <%= f.text_field :name %><br />
        </div>
        <div class="field">
          <%= f.label 'Duration' %>
          <%= f.text_field :duration %><br />
        </div>
        <div class="actions">
          <%= f.submit 'Save Job' %>
        </div>
    <% end %>
  </div>
</div>

app/views/jobs/index.html.erb
<% provide(:title, 'All jobs') %>

<% if @objective_function_value!=nil %>
<h1>Solution</h1>
Objective function value: <b><%=   @objective_function_value %></b><br>   <br>   <br>
    <table class="table" id="jobs">
      <tr>
        <th>Name</th>
        <th>Duration</th>
        <th>FEZ</th>
        <th>SEZ</th>
        <th>Begin</th>
        <th>End</th>
        <th></th>
      </tr>

      <% @jobs.each do |job| %>
          <tr>
            <td><%= job.name %></td>
            <td><%= job.duration %></td>
            <td><%= job.fez %></td>
            <td><%= job.sez %></td>
            <td><%= job.begin %></td>
            <td><%= job.end %></td>
          </tr>
      <% end %>
    </table>

   <br>
    <div class="navigation-left" style="float:left">
      &lArr; <%= link_to  'Go to Main Menu', current_user %>    </div><br>

<%else%>
<h1>Jobs</h1>
    <table class="table" id="jobs">
      <tr>
        <th>Name</th>
        <th>Duration</th>
       <th></th>
      </tr>

      <% @jobs.each do |job| %>
          <tr>
            <td><%= best_in_place job, :name, :type => :input %></td>
            <td><%= best_in_place job, :duration, :type => :input %></td>
            <td><%= link_to 'Destroy', job, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
    </table>

<br/>

<%= link_to 'Create a new Job', new_job_path %><br> <br>

<div class="navigation-left" style="float:left">
  &lArr;  <%= link_to 'Go Back to Resources', resources_path %>  </div>
<div class="navigation-left" style="float:right">
<%= link_to 'Continue with Relations', relations_path %>     &#8658;    </div> <br>
<div class="navigation-left" style="float:left">
  &lArr; <%= link_to  'Go to Main Menu', current_user %>    </div><br>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>
<%= render 'form' %>
<%= link_to 'Back', jobs_path %>