config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :jobs
  resources :resources
  resources :consumptions
  resources :relations

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/gtc', to: 'static_pages#gtc'

  match 'resources/new_project', :to => 'resources#new_project'
  match 'users/update_project', :to => 'users#update_project'
  match 'jobs/delete_solution', :to => 'jobs#delete_solution'
  match 'jobs/solve_problem', :to => 'jobs#solve_problem'
  match 'jobs/load_project', :to => 'jobs#load_project'

end

app/views/resources/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@resource) do |f| %>
        <% if @resource.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

              <ul>
                <% @resource.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label 'Name' %>
          <%= f.text_field :name %><br />
        </div>
        <div class="field">
          <%= f.label 'Capacity' %>
          <%= f.text_field :capacity %><br />
        </div>
        <div class="actions">
          <%= f.submit 'Save resource' %>
        </div>
    <% end %>
  </div>
</div>

app/views/resources/edit.html.erb
<h1>Update Resources</h1>

<%= render 'form' %>

<%= link_to 'Show', @resources %> <br><br>
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Resources</h1>
<table class="table" id="resources">
  <tr>
    <th>Name</th>
    <th>Capacity</th>
    <th></th>
  </tr>

  <% @resources.each do |resource| %>
      <tr>
        <td><%= best_in_place resource, :name, :type => :input, :nil => "Click me to add content!" %></td>
        <td><%= best_in_place resource, :capacity, :type => :input %></td>
        <td><%= link_to 'delete', resource, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'Create a new Resource', new_resource_path %><br>

<div class="navigation-left" style="float:right">
 <%= link_to 'Continue with Jobs', jobs_path %> &#8658;    </div><br>

<div class="navigation-left" style="float:left">
  &lArr; <%= link_to  'Go to Main Menu', current_user %>    </div><br>




app/views/resources/new.html.erb
<h1>New Resource</h1>
<%= render 'form' %>
<%= link_to 'Back', resources_path %>